### ISSUE TITLE
2 tsconfig.json

### ISSUE THREAD

**Issue by icarogtavares** [matheusdavidson/express-typescript-mongoose-starter#3]
Porque tem um tsconfig.json na pasta raiz e outro na pasta src?

**Comment by matheusdavidson** [comment]
O ```tsconfig.json``` da raiz controla algumas configurações globais, enquanto o da pasta src serve apenas para informar o diretório onde o ```tsc``` vai jogar os arquivos ```.js``` transpilados. 

Se você notar no arquivo do diretório ```src``` eu extendo o da raiz:
```"extends": "../tsconfig.json"```
